version: '2'

services:
  virtualtheque-web:
    container_name: container-apache-virtualtheque
    build :
      context: ./
      dockerfile: docker/www-virtualtheque/Dockerfile
    ports:
      - 80:80
      - 443:443
    links:
      - db
    networks:
      virtualtheque_net:
         ipv4_address: 172.16.0.2
  db:
    container_name: container-mysql-virtualtheque
    build:
      context: docker/database-virtualtheque
      dockerfile: Dockerfile
    environment:
      MYSQL_DATABASE: bibliothequevirtuelle
      MYSQL_ROOT_PASSWORD: ${VIRTUALTHEQUE_DATABASE_PASSWORD}
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: ${VIRTUALTHEQUE_DATABASE_PASSWORD}
    restart: always
    volumes:
      - ./docker/database-virtualtheque/data:/docker-entrypoint-initdb.d
    networks:
      virtualtheque_net:
         ipv4_address: 172.16.0.3

networks:
  virtualtheque_net:
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/24
